### ISSUE TITLE
Typo in the guide for challenge "triangular"

### ISSUE THREAD

**Issue by Lancern** [danprince/wasm-challenges#2]
The guide says "returns 1 when $n <= 0":

https://github.com/danprince/webassembly-wizardry/blob/8f7e9124694e471d96ad544772e40e5996d41498/triangular.wat#L3

But the test case requires it return 0 when $n <= 0:

https://github.com/danprince/webassembly-wizardry/blob/8f7e9124694e471d96ad544772e40e5996d41498/tests.mjs#L175

https://github.com/danprince/webassembly-wizardry/blob/8f7e9124694e471d96ad544772e40e5996d41498/tests.mjs#L193-L195

**Comment by danprince** [comment]
All fixed. Thanks @Lancern!
